Remove datetime_safe (#1258)
This was only required for older versions of Python that did not support
`strftime` on dates before 1900. Faker no longer supports those versions
of Python.

```
Python 2.7.17 (default, Dec 23 2019, 21:25:34)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime(1800, 12, 11)
datetime.datetime(1800, 12, 11, 0, 0)
>>> datetime.datetime(1800, 12, 11).strftime('%Y-%m-%d')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: year=1800 is before 1900; the datetime strftime() methods require year >= 1900
```

```
Python 3.5.9 (default, Sep 10 2020, 22:25:21)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime(1800, 12, 11)
datetime.datetime(1800, 12, 11, 0, 0)
>>> datetime.datetime(1800, 12, 11).strftime('%Y-%m-%d')
'1800-12-11'
```