Type error on calling Faker from within an internal pytest fixture
For reasons I don't understand yet, pytest is calling this private fixture
during the setup phase of the tests. Regardless the reason, the code contains a
bug since it expects a `string` but the `_session_faker` constructs a `List`
before calling the constructor

* Faker version: 0.7.4
* OS: `Ubuntu 14.04.6 LTS. travis`
* Python: 3.6.5

```
request = <SubRequest '_session_faker' for <TestCaseFunction test_get_access_method_for_event>>
    @pytest.fixture(scope='session', autouse=True)
    def _session_faker(request):
        """Fixture that stores the session level ``Faker`` instance.

        This fixture is internal and is only meant for use within the project.
        Third parties should instead use the ``faker`` fixture for their tests.
        """
        if 'faker_session_locale' in request.fixturenames:
            locale = request.getfixturevalue('faker_session_locale')
        else:
            locale = [DEFAULT_LOCALE]
>       return Faker(locale=locale)
../../../virtualenv/python3.6.5/lib/python3.6/site-packages/faker/contrib/pytest/plugin.py:20:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cls = <class 'faker.factory.Factory'>, locale = ['en_US'], providers = None
generator = None, includes = [], config = {}
    @classmethod
    def create(cls, locale=None, providers=None, generator=None, includes=None, **config):
        if includes is None:
            includes = []

        # fix locale to package name
>       locale = locale.replace('-', '_') if locale else DEFAULT_LOCALE
E       AttributeError: 'list' object has no attribute 'replace'
../../../virtualenv/python3.6.5/lib/python3.6/site-packages/faker/factory.py:22: AttributeError
```

The stacktrace that leads to this execution is the following

```
-> "__main__", mod_spec)
  /opt/python/3.6.5/lib/python3.6/runpy.py(85)_run_code()
-> exec(code, run_globals)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pytest.py(102)<module>()
-> raise SystemExit(pytest.main())
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/config/__init__.py(82)main()
-> return config.hook.pytest_cmdline_main(config=config)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/hooks.py(286)__call__()
-> return self._hookexec(self, self.get_hookimpls(), kwargs)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/manager.py(93)_hookexec()
-> return self._inner_hookexec(hook, methods, kwargs)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/manager.py(87)<lambda>()
-> firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/callers.py(187)_multicall()
-> res = hook_impl.function(*args)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/main.py(243)pytest_cmdline_main()
-> return wrap_session(config, _main)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/main.py(206)wrap_session()
-> session.exitstatus = doit(config, session) or 0
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/main.py(250)_main()
-> config.hook.pytest_runtestloop(session=session)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/hooks.py(286)__call__()
-> return self._hookexec(self, self.get_hookimpls(), kwargs)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/manager.py(93)_hookexec()
-> return self._inner_hookexec(hook, methods, kwargs)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/manager.py(87)<lambda>()
-> firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/callers.py(187)_multicall()
-> res = hook_impl.function(*args)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/main.py(271)pytest_runtestloop()
-> item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/hooks.py(286)__call__()
-> return self._hookexec(self, self.get_hookimpls(), kwargs)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/manager.py(93)_hookexec()
-> return self._inner_hookexec(hook, methods, kwargs)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/manager.py(87)<lambda>()
-> firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/callers.py(187)_multicall()
-> res = hook_impl.function(*args)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/runner.py(78)pytest_runtest_protocol()
-> runtestprotocol(item, nextitem=nextitem)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/runner.py(87)runtestprotocol()
-> rep = call_and_report(item, "setup", log)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/runner.py(173)call_and_report()
-> call = call_runtest_hook(item, when, **kwds)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/runner.py(198)call_runtest_hook()
-> lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/runner.py(226)from_call()
-> result = func()
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/runner.py(198)<lambda>()
-> lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/hooks.py(286)__call__()
-> return self._hookexec(self, self.get_hookimpls(), kwargs)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/manager.py(93)_hookexec()
-> return self._inner_hookexec(hook, methods, kwargs)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/manager.py(87)<lambda>()
-> firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/callers.py(187)_multicall()
-> res = hook_impl.function(*args)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/runner.py(116)pytest_runtest_setup()
-> item.session._setupstate.prepare(item)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/runner.py(362)prepare()
-> col.setup()
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/unittest.py(119)setup()
-> self._request._fillfixtures()
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/fixtures.py(469)_fillfixtures()
-> item.funcargs[argname] = self.getfixturevalue(argname)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/fixtures.py(479)getfixturevalue()
-> return self._get_active_fixturedef(argname).cached_result[0]
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/fixtures.py(502)_get_active_fixturedef()
-> self._compute_fixture_value(fixturedef)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/fixtures.py(587)_compute_fixture_value()
-> fixturedef.execute(request=subrequest)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/fixtures.py(894)execute()
-> return hook.pytest_fixture_setup(fixturedef=self, request=request)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/hooks.py(286)__call__()
-> return self._hookexec(self, self.get_hookimpls(), kwargs)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/manager.py(93)_hookexec()
-> return self._inner_hookexec(hook, methods, kwargs)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/manager.py(87)<lambda>()
-> firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/pluggy/callers.py(187)_multicall()
-> res = hook_impl.function(*args)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/fixtures.py(936)pytest_fixture_setup()
-> result = call_fixture_func(fixturefunc, request, kwargs)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/_pytest/fixtures.py(795)call_fixture_func()
-> res = fixturefunc(**kwargs)
  /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/faker/contrib/pytest/plugin.py(20)_session_faker()
-> return Faker(locale=locale)
> /home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/faker/factory.py(28)create()
```